"""Build data/plan.json, module 1: the plan and the first year, 1904–1906.

Sources (public domain, all American publications before 1931), each passage read against the page image:
- "The Proposed Railroad to Key West," Scientific American 92:7 (18 February 1905), p. 139
  (archive.org sim_scientific-american_1905-02-18_92_7, image n2).
- "The Florida East Coast Extension to Key West," The Railroad Gazette 39:14 (6 October 1905), pp. 324 and 326
  (archive.org sim_railway-age_1905-10-06_39_14, images n15 and n17; p. 325 is a plate of drawings).
- Harry C. Smith, "Key West Extension of the Florida East Coast," The Railroad Gazette 40:16 (20 April 1906),
  pp. 404–406 (archive.org sim_railway-age_1906-04-20_40_16, images n11–n13).
- Florida East Coast Railway, Key West Extension of the Florida East Coast Railway, opened January 22, 1912
  (company booklet, 1912; archive.org keywestextension00flor, Smithsonian Libraries). The booklet has no page
  numbers; passages are cited by the scan image (page/nN on archive.org).
The text follows the printing, including its spellings ("rythmical", "threshhold", "Estetta"); OCR errors
are corrected at the image; words broken at the end of a line are joined.
Run from the repository root:  python tools/build-plan.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "plan.json"

SA = "Sci. Am. 92 (1905), p. 139"
RG5 = "R.R. Gazette 39 (1905), p. {}"
RG6 = "R.R. Gazette 40 (1906), p. {}"
BK = "Booklet 1912, scan n{}"

SECTIONS = [
 {"id": "why", "zk": "Why", "titel": "Why Key West, 1903–1905",
  "blurb": "What the line was for, in the words of those who announced and built it: a harbour for ships too deep for Miami, a car ferry to Havana, and the Panama Canal. The engineering press of 1905 and the company's booklet of 1912, which tells how the decision was taken.",
  "units": [
   (1, "The most notable feat", SA,
    "One of the most interesting chains of islands off the American coast is the Florida keys, of which Key West forms a part. They constitute a chain of land links stretching out into the ocean from the mainland, and forming the passage known as the Florida Straits. A glance at the map shows that they are separated from one another by channels varying from a few hundred feet to several miles in width. In fact, between some of the keys the distance is so great that it would seem impossible to connect them with a bridge or other structure, but this is what is to be done, for engineers have recently completed plans and surveys for what is undoubtedly the most notable feat in railroad engineering which has ever been conceived—the construction of a railway to Key West by means of these islands.",
    "The opening of the first report in the general press, February 1905, two months before construction began."),
   (2, "Two years of surveys", SA,
    "During the last two years, a corps of engineers in charge of Mr. E. Ben Carter, of the Florida East Coast system, have been making an exhaustive investigation, to determine if the extension was practicable. The territory between the southern terminus of the railway and the coast line, as well as all of the keys, and the waters separating them, have been carefully examined, with the result that the extension has been deemed possible. But before Key West can be reached, it will be necessary to build 120 miles of railway on the keys and over the sounds and other passages separating them. In all, twenty islands are available for the extension, but no less than 40 miles of elevated work must be built above the water, not counting the trestling between Key Largo and the mainland.",
    "In February 1905 the article still expected the elevated work, apart from the bridges, to stand on steel posts or piling; by October the plan was rock embankment and concrete arches ([7]–[9])."),
   (3, "Havana and the canal", SA,
    "The building of this extension, however, will give the railroad in question access to one of the finest harbors on the American coast, that of Key West, which has a depth of 33 feet in the main entrance. The harbor is accessible by four different passages, and is sufficiently commodious to accommodate a considerable fleet of ocean-going vessels. It is understood that one reason for building the extension is to establish a transfer service between Key West and Havana, so that freight can be shipped from this country to Cuba by the carload without breaking bulk en route. Havana is about 90 miles from Key West, and a car-ferry steamer having a speed equal to the ferryboats on the North River could readily make the round trip in a day of ten hours. In connection with the Panama Canal, however, Key West possesses special advantages, as it is actually 250 miles nearer the Gulf entrance to the canal than any other city in the United States. Consequently, with railroad communication, it would offer special facilities as the port for lines of steamships to the American and Asiatic Pacific coast, as well as the islands of the Pacific.",
    "The car ferry to Havana came in 1915; the traffic through Key West to the canal never did. Module 6 follows what the line actually carried."),
   (4, "Cuba since the war with Spain", RG5.format(324),
    "The project of Mr. H. M. Flagler, President of the Florida East Coast Railway, to build a railroad over the Florida Keys to Key West, after a number of years of careful estimate and study, has finally reached the stage of actual construction and grading is in progress on some of the northern islands over which the road will run. The present southern seaport terminus of the Florida East Coast is at Miami, from where the Peninsular & Occidental Steamship Co.'s boats run to Nassau, Key West and Havana. From Miami to Key West by boat is 165 miles and to Havana 240 miles. Only shallow draught boats can be used in this service, however, because of the shallow water in Miami harbor. Key West has an excellent harbor and is only 90 miles from Havana. Since the war with Spain, Cuba has experienced a tremendous commercial development and as a winter resort it has also become very popular. For these two reasons the new line, which promises to afford much better facilities for communication between Cuba and the mainland, seems to justify the hopes of its promoter as to future traffic.",
    "The Railroad Gazette, the trade weekly of American railway officers, October 1905."),
   (5, "\"Are you sure this railway can be built?\"", BK.format(22),
    "On the 18th of November, 1903, the republics of the United States and Panama signed that convention which determined the completion of the Panama Canal. The winter following, Mr. Flagler and Mr. Parrott studied preliminary surveys and engineers' reports in a new light. At the end of the winter, Mr. Flagler closed a conference with Mr. Parrott with the question, \"Are you sure this railway can be built?\" Mr. Parrott answered, \"I am sure.\" \"Very well,\" said the capitalist, with the courage of Columbus, \"go ahead.\" Thus simply and earnestly, the great project had its beginning which was full of the promise of its completion.",
    "The company's own account, written for the opening in 1912. Joseph R. Parrott was then vice-president and general manager, from 1909 president of the railway. No other source for the conversation has been found."),
   (6, "\"Time is money\"", BK.format("16–17"),
    "Key West, with its large area, its deep water, its populous and busy modern life, is the southernmost port in the United States. Strategically, it is the key to and the protection of all the ports on the extended shore line of the Gulf of Mexico. Since the genius of our Government has made the Panama Canal a fact in the world's commerce, Key West has assumed new and great importance. Coupled with this, the spirit of our modern commerce calls for rapid transit wherever the inventiveness and enterprise of man can bring it into service. Never before was the adage \"time is money\" so true as it is to-day. There are men whose minutes are worth millions.",
    "The company's booklet of 1912, after the canal treaty: Key West as the port nearest the canal."),
  ]},
 {"id": "line", "zk": "Line", "titel": "The line as planned, 1905",
  "blurb": "The route and the way it was to be built, as the Railroad Gazette described it in October 1905: rock embankment where the water was shallow, concrete arches where the openings were exposed to storms, and a fleet of barges, tugs and quarter boats. Smith's report of April 1906 adds the route that was given up.",
  "units": [
   (7, "Embankment or arch", RG5.format(324),
    "The accompanying map shows the route of the projected road over the Keys from Homestead, Fla., the present terminus, 28 miles south of Miami, to Key West 126 miles. The long chain of islands extending out from the mainland has been made use of as far as possible, but only about 65 miles will be built on a natural foundation. The remainder of the line is to be built on rock embankments and reinforced concrete arch viaducts. Starting from Homestead the line runs southeast leaving the mainland at the crossing of Jewfish creek and on out onto Key Largo, the longest of the keys. For about 15 miles it runs through the center of this narrow island and then follows the line of the Keys out to Key West. Nearly 30 islands are used for short stretches. Where the intervening water is shallow, a rock embankment will be built, but where the water is deeper and the opening is exposed to storms by breaks in the outer reef, the concrete arch viaduct construction will be used. In the rock embankments there will be a number of 25-ft. openings to allow for the passage of row boats and small craft, and where the line crosses three important channels drawbridges will be put in to pass larger vessels.",
    "The rule that decided the line: fill where the water is shallow, arches where the sea comes through the reef. It is the choice the company revised after the storms of 1909 and 1910 (module 5), and the one that decided in 1935 what stood (module 7)."),
   (8, "Four viaducts and the storms", RG5.format("324, 326"),
    "The most difficult part of the work will be, of course, the construction of the concrete arch viaducts. There are four of these, aggregating 5.78 miles in length, as follows: From Long Key to Conch Key 10,500 ft., Knight's Key Channel 7,300 ft., Moser Key form of construction to be used is 50-ft. reinforced concrete circular arch spans and piers, but in some places 60-ft. spans will be used. The water is shallow in most places, from 10 to 30 ft. deep, and the bottom is limestone, but as these waters are frequently disturbed by severe and sudden storms much difficulty is looked for in placing the concrete. A further difficulty lies in the fact that all material, including the broken stone for the concrete, must be shipped by boat from Miami. A good quality of limestone is quarried near Miami and this will be used on most of the work.",
    "Between \"Moser Key\" and \"form of construction\" the printing has lost at least one line, with the length of the fourth viaduct; the gap is in the original (p. 326, first line)."),
   (9, "Thirty-one feet above low water", RG5.format(326),
    "The drawings show the details of the arches and the method of reinforcement. On account of the severity of the storms which prevail it will be necessary to firmly anchor the piers to the bottom to prevent shifting out of line. Piles will be sunk into the rock and carried up to within 2 ft. of the springing line of the arches. In the abutment piers which are to be put in at every fifth arch 28 piles are used and in the intermediate piers 21 piles are used. The arches are reinforced with circumferential square corrugated bars near the outside surfaces and with transverse bars which are tied together with ½-in. round radial bars. Earth filling will be put in between the spandrel walls and the ballast laid on top of this above the level of the concrete coping. This will bring the base of rail about 31 feet above the mean low water level. The estimated amount of material to be used in the concrete arches is 206,100 cu. yds. of sand, 286,800 barrels of hydraulic cement, 176,900 cu. yds. of stone and 4,810 tons of steel.",
    None),
   (10, "Four quarter boats", RG5.format(326),
    "A working base will be established at Bahia Honda Harbor, 40 miles north of Key West, where there is from 18 to 28 ft. of water and a good entrance channel. For construction work the following floating equipment will be used: 6 tugs. 1 stern-wheel steamer. 16 barges, 25 ft. x 100 ft. 24 barges, 30 ft. x 100 ft. 12 barges, 20 ft. x 80 ft. 1 sand dredge. 1 earth dredge for filling the concrete viaducts. 8 barges, 40 ft. x 70 ft., with concrete mixers and hoists. 8 pile drivers. 8 towing launches. 1 despatch boat. 4 quarter boats. 100 dinghys.",
    "The quarter boats were the floating barracks of the workers. A year later, in October 1906, the hurricane carried them out to sea (module 3)."),
   (11, "The route given up", RG6.format(404),
    "Four long viaducts are to be built, the longest and most troublesome being for the seven miles between Boot Key and Bahia Honda. It will stretch over water from 10 to 30 ft. deep. It was originally intended to keep to the Florida mainland as far as Cape Sable and then cross by a viaduct 35 miles long, directly to Key West, but the depth of the water most of the distance ruled out that plan. Instead, the extension is being made from Homestead southwestward over a stretch of the Everglades called Big Prairie by dredges which throw up an embankment. This, in the opinion of the engineers, is the most noteworthy work ever attempted. Only a short span will be necessary from the mainland to Key Largo at Jew Fish Creek. But shallow water in the vicinity has caused much annoyance to the fleet of construction boats, so that a big dredge has been stationed there.",
    None),
   (12, "Lake Surprise", RG6.format("404–405"),
    "Soon after reaching Largo, the surveyors found a large lake to be crossed, which had never been mentioned on the maps. Accordingly it was christened Lake Surprise. A dredge is at work there sucking up the peaty bottom of the lake, which is dumped into a hopper and then forced through big pipes supported by pontoon bridges for a quarter of a mile to the point where an embankment for the railroad track across the lake is being built. The only foundation the key offers at this point is mangrove roots.",
    None),
  ]},
 {"id": "first", "zk": "First year", "titel": "The first year, 1905–1906",
  "blurb": "Harry C. Smith toured the work in the winter of 1905–1906 on a launch with the assistant engineer William J. Krome and wrote for the railway trade press. His report is friendly to the company, and it records what the company's booklet of 1912 leaves out: separate camps for Black and white workers, the complaints that reached the courts, a strike at Key West, and men put to work on the streets as vagrants.",
  "units": [
   (13, "Landscape gardening", RG6.format(404),
    "Unexpected progress has been made to date on the Key West extension of the Florida East Coast Railroad despite numerous difficulties, and indications point to the completion of the tremendous task much earlier than the most sanguine engineers predicted at the outset. A large share of the land work across the keys has been finished, although it is less than a year since construction was actually begun and hardly ten months have elapsed from the date that a large force began work. The construction gang is about to transfer itself to the water stretches, which, for the most part, do not interpose any decided obstacles. Of course, there still remains a good deal of land work to be done in spots, but it is desirable, if not absolutely necessary, to avoid the thickets on the keys during the warmer months when the mosquitos constitute a serious menace. For rather more than half of the 165 miles between Miami and Key West, the railroad will be over water, but only at two or three points is there much depth. In fact, it is, as Henry M. Flagler says, as much like landscape gardening as it is railroad building. Building the reinforced concrete arches is not as great a problem as is their protection from the tropical storms at the few points not guarded by reefs, before and after completion. This difficulty caused contractors to be somewhat slow in bidding and it is not unlikely, therefore, that the Florida East Coast Co. will do part of the work itself.",
    "The company did the work itself, with no contractor for most of it (Patterson, Railway Age Gazette 1912; module 2). The line reached Key West six years later, not \"much earlier\"."),
   (14, "Kept apart", RG6.format(405),
    "The first actual construction camp at which I stopped in making a tour on the launch \"Nan\" with William J. Krome, principal assistant engineer, was composed entirely of negroes. It was after dark and they mistook the launch for the pay boat, as is often the case. The whole camp began a rythmical clapping of hands in the tents, which, from a distance, seemed like the fervent devotions of a colored camp meeting. Negroes, with a few exceptions, clear the jungles as an advance guard. They are selected because they are commonly immune to certain poisonous plants frequently found. The work is done on contract, bids by the square foot or yard being received. Such contractors make better wages than ordinary laborers. There is another all-negro camp on Key Vaca, the only other exclusively black settlement. With one or two exceptions, the whites and negroes are carefully kept apart. At Plantation Key there is a mixture, but the negroes are isolated on one side of the embankment.",
    "Smith's words and his view, quoted as printed. The claim of immunity to poisonous plants is his, not a finding. Black workers cleared the jungle ahead of the line, in camps of their own."),
   (15, "The camps", RG6.format(405),
    "The other camps are on Umbrella, Upper Matecumbe, Lower Matecumbe, Long, Crall, Vaca (two), Summerland, Ramrod and Cudjoe Keys and Key West. The average camp roll is from 200 to 250 men, there being a constant shifting from one to another, particularly within the same division, of which there are three or four, each under the general oversight of a section engineer.",
    None),
   (16, "Complaints that reached the courts", RG6.format(405),
    "All winter the newspapers have been filled with stories of suffering and deprivation alleged by laborers from New York and Philadelphia, who went South to do the earlier construction work. Some of these complaints have already reached the courts. On the other hand, equally vehement denials have been made by officials of the Florida East Coast road. It is true that hardships existed at the threshhold of the work, but they have been so reduced steadily that the path ahead seems comparatively smooth. There was acute distress in December, because of a tremendous rainfall that month. Weather bureau reports show that the precipitation was 15.18 in., or 14.67 in. more than that of December, 1904. The average December rainfall for 18 years has been 3.13 in.",
    "The complaints led to indictments and to the peonage trial in New York in 1908 (module 4)."),
   (17, "The would-be laborers", RG6.format(405),
    "Many consumptives and infirm persons, anxious to spend the winter in a warmer clime, applied at the New York employment agencies and the same motive actuated a large percentage of the able-bodied applicants. A physical test was imposed, but it largely failed of its purpose, because many of the successful applicants either sold or gave way their tickets, while some of those who arrived at the keys had apparently exchanged good arms and legs for those of the wooden variety, during their journey. Some sort of photographic identification should have been tried. A good many of the would-be laborers disappeared soon after the trains reached Florida. Now negroes are shipped by boat to Key West to avoid their exodus from trains at Jacksonville. Few of the arrivals brought more than a handful of baggage, and the coquina rock that covers most of the keys in the few days tore even the stoutest shoes to pieces. Living in tents during the December downpour was no joke.",
    "The company's explanation of the complaints, through the reporter: the men who complained were not fit to work, or not workers at all."),
   (18, "The strike at Key West", RG6.format(405),
    "At the camp on the easterly end of Key West the men struck early. A big body of them marched to town, surrounded the city hall and demanded food. For two days the city fed them on the baseball grounds by public subscription. Then a local grocer offered to feed the force for 45 cents a day each, and the business men of Key West forced them to return to work. A few were kept busy on Key West streets as vagrants serving out terms. Some long ago worked out their service, but preferred to remain as boarders at the city lockup.",
    "How the business men \"forced\" the strikers back to work, Smith does not say. A few of the men served terms as vagrants on the streets of Key West; a year later the company explained the stories of peonage by such sentences (Spooner, Railroad Gazette 1907; module 4)."),
   (19, "Every drop by lighter", RG6.format("405–406"),
    "The construction gangs eat in long tents much in military fashion. The food while rather coarse and not served in appetizing style, has been wholesome and fairly well varied. One of the greatest problems has been the water supply. Wells on the keys furnish only salt water. At Key West rain water is exclusively used. So every drop has to be transported on lighters from Miami in tanks holding from 5,200 to 6,000 gallons. Eventually this water may be pumped in pipes, some of it the whole distance of 165 miles. Several times there has been lively scurrying to prevent a water famine in some of the camps.",
    None),
   (20, "Ten hours, ten tons", RG6.format(406),
    "As things stand at present, the commissary stores at the camps run by a Miami grocer offer the greatest field for improvement. There has been little sickness and few accidents considering the carelessness of many of the men. The money derived from the commissary privilege by the railroad company goes to the support of the camp hospitals and the general institution at Miami. As something like ten tons of dynamite are used each week for blasting, the question of storing the explosive is important. One boat, so far, has carried all the dynamite from Miami to the two or three lighters, kept as magazines a couple of miles off shore with a watchman aboard. A day's work consists of ten hours, starting about 6 a.m. and ending at 5 p.m. Many are put drilling for dynamite blasts by steadily dropping iron rods into the coquina rock. Others shovel, while still others work with wheel-barrows or drive mule carts. A channel wide enough for a small river is blasted along the surface. The rocks and gravel thus obtained are then thrown up at one side, forming the railroad embankment.",
    None),
  ]},
 {"id": "engineers", "zk": "Engineers", "titel": "The engineers and the men, as the company told it in 1912",
  "blurb": "The booklet the railway published for the opening: the chief engineer it found in Mexico, his successor, and the men \"of almost every nation and every shade of color\" in the company's own words and categories.",
  "units": [
   (21, "An engineer from Tampico", BK.format(23),
    "Naturally, the first requisite to the successful prosecution of the work was an engineer with sufficient courage to undertake it at all, and sufficient skill to meet its many difficulties. This engineer was found in the person of Joseph Carroll Meredith, who was at that time engaged in construction work on the great docks in the harbor of Tampico, Mexico. Having considered the project of the oversea railway as outlined to him, Mr. Meredith was appointed Chief Constructing Engineer and entered on his duty the 22d of July, 1904. From the moment he began his work, Mr. Meredith displayed a modest spirit, an unwavering determination, and a superior skill, facing every danger, meeting every difficulty. His plans were laid months in advance of the work and practically every detail for the final completion of the work had been put on paper at the time of his death. This untimely event occurred suddenly, the 20th of April, 1909, bringing the sincerest sorrow and the deepest regret to both his superiors and his subordinates.",
    None),
   (22, "The actual work", BK.format(28),
    "The actual work of construction south of Homestead began in April, 1905, under the immediate charge of Mr. Meredith until his death, the 20th of April, 1909. Mr. Meredith was succeeded by his first assistant, Mr. W. J. Krome, who took up his work with the courage of his predecessor, to which he added his own enthusiasm and determination. Notwithstanding the plans which Mr. Meredith had laid for the completing of the work, there were constant emergencies and unexpected contingencies arising. All these Mr. Krome met with alert intelligence and ready skill. Throughout his work he has been ably assisted by Messrs. P. L. Wilson, C. S. Coe, G. R. Smiley, and Ernest Cotton, as Division Engineers; Mr. R. W. Carter, as Bridge Engineer; Mr. E. H. Sheeran, as General Foreman; and Mr. B. A. Deal, as Auditor of Construction.",
    "The booklet names the engineers and foremen; none of the workers is named in it."),
   (23, "Every shade of color", BK.format(28),
    "During all this time \"the grade\" has been a teeming hive of industry. Men of almost every nation and every shade of color were gathered for the labor. There were hardy Northmen from Sweden and Norway, mainly filling positions as foremen and overseers. There were Spaniards in great numbers, coming to the work, by way of Cuba, from the northern provinces of Spain. There were American negroes, and negroes from the Bahamas and the Lesser Antilles. Men from Grand Cayman were there, all negroid, though some were black and some almost white. There were divers from Greece, and a horde of nondescripts, many of whom had known and loved \"The Bowery\" all their lives.",
    "The company's categories of 1912, quoted as printed: Scandinavians as foremen, the others by origin and colour, the recruits from New York as \"nondescripts\" from the Bowery."),
   (24, "\"So little loss of human life\"", BK.format("28–29"),
    "It is doubtful whether ever before in similar work the same care and attention were given to the labor element. Whether they were housed in boats or barracks, every precaution was taken to assure their health and safety. Food of only the best quality was provided in abundance, and everything needful for comfort and recreation was supplied. Ample provision was made for illness or injury \"on the grade,\" and the railway hospital at Miami was especially equipped to meet the exigencies of the service. Many of the men who labored on the work were better housed and fed, cared for and paid, than they had ever been in all their lives. Loss of life was met with, to be sure, but it is doubtful whether any similar work, in such conditions, could be carried to completion with so much content among the men employed and so little loss of human life.",
    "The booklet gives no number of the dead. For the storm of October 1906 alone, the Weather Bureau's offices reported more than 100, about 135 and 124 (module 3)."),
  ]},
 {"id": "promise", "zk": "Promise", "titel": "What the company promised, 1912",
  "blurb": "The booklet's construction data and its claims for the finished line: 17.2 miles of bridges, some twenty miles of embankment protected by marl, a roadbed \"above hurricane tides\", and a line \"of practically storm-proof construction\". Module 7 shows what the hurricane of 1935 made of these claims.",
  "units": [
   (25, "Construction data", BK.format("39–40"),
    "Surveys south of Homestead with Key West as an objective point were begun in January, 1904. The first construction work was commenced in April, 1905, and the line was opened to traffic as far south as Knights Key Dock in February, 1908. The total distance from Homestead to Key West Terminal is 128.4 miles. With the completion of the work there will be 17.2 miles of permanent bridge work, including 11.1 miles of concrete arch viaducts and 6.1 miles of steel bridging resting on concrete piers. The longest bridge is between Knights Key and Little Duck Key, which, with approaches, is over 7 miles in length. Other long bridges are located at Bahia Honda, where through steel trusses up to 243 feet spans are used; and at Long Key Viaduct, a structure of reinforced concrete arches; the remainder of the water spaces, probably 20 miles or more, will be embankment work protected by marl slopes. The greatest depth of water encountered was at Bahia Honda Harbor, where the foundations of some of the piers are 30 feet below tide level.",
    "Against the plan of 1905 ([8]): 5.78 miles of arch viaduct planned, 11.1 miles built."),
   (26, "Forty-nine miles by dredge", BK.format(40),
    "Across the more shallow water openings and low, swampy Keys, the roadbed was built by dredges and traveling excavators, which dug the material from alongside and constructed the embankments ahead of them. A great deal of this type of work necessitated the blasting of the limestone under water, in order to secure the material required to build the embankments. A total distance of 49 miles of this line was constructed by these methods.",
    None),
   (27, "\"Practically storm-proof\"", BK.format("40–41"),
    "The roadbed, along the portions of the line which are exposed to the destructive action of the sea during storms, is being protected by the application of a heavy layer of marine marl. This material is dug by dredges from deep deposits near the line and is loaded into trains of steel dump cars which operate on long trestles built out into the marl beds. It is hauled to the points where needed and when dumped from the cars flows out to a very flat slope. This marl hardens after exposure to the air and forms a solid protective coating, which has been proven capable of withstanding the heaviest hurricane seas, when the largest rock rip-rap was entirely washed away. The roadbed on the Keys is built of the native limestone blasted from along the right of way and is of sufficient height to be above hurricane tides. With the deeper waterways spanned by concrete and steel bridges, the embankments across the shallow openings protected by marl slopes, and the roadbed on the Keys secured from damage by the dense jungle intervening between the open water, the line when completed will be of practically storm-proof construction.",
    "On 2 September 1935 one observer on the keys recorded the water \"3 feet from top of railroad grade, or about 16 feet\" (Monthly Weather Review, September 1935). The Interstate Commerce Commission later put the destruction of roadbed and track between mileposts 430 and 470 (module 7)."),
   (28, "\"It will endure throughout the ages\"", BK.format(30),
    "That it is accomplished seems incredible to one who sailed that stretch of sweeping sea now dominated and beautified by the matchless lines and mighty proportions of the Long Key Viaduct. This viaduct alone is a monument to a whole lifetime of constructive skill and enterprise. It will endure throughout the ages. Its sweeping arches will gleam in the sunshine of centuries. Its mighty bulwarks will welcome the beating protests of the hurricane and, like the faith of the man whose genius for building inspired it, it will stand firm, unshaken, indestructible.",
    "The viaducts did stand in 1935, and from 1938 carried the Overseas Highway on their piers (National Park Service, 1938; module 7). The Long Key viaduct still stands."),
  ]},
]


def main():
    sections = []
    for s in SECTIONS:
        units = []
        for n, titel, pg, en, note in s["units"]:
            u = {"n": n, "pg": pg, "titel": titel, "en": en}
            if note:
                u["note"] = note
            units.append(u)
        sections.append({k: s[k] for k in ("id", "zk", "titel", "blurb")} | {"units": units})
    data = {
        "titel": "The plan and the first year, 1904–1906",
        "autor": "Scientific American (February 1905); The Railroad Gazette (October 1905); Harry C. Smith in The Railroad Gazette (April 1906); the Florida East Coast Railway's booklet for the opening (1912)",
        "jahr": "1903–1912",
        "quelle": "\"The Proposed Railroad to Key West,\" Scientific American 92:7 (18 Feb. 1905), p. 139 (archive.org sim_scientific-american_1905-02-18_92_7); \"The Florida East Coast Extension to Key West,\" The Railroad Gazette 39:14 (6 Oct. 1905), pp. 324, 326 (archive.org sim_railway-age_1905-10-06_39_14); Harry C. Smith, \"Key West Extension of the Florida East Coast,\" The Railroad Gazette 40:16 (20 Apr. 1906), pp. 404–406 (archive.org sim_railway-age_1906-04-20_40_16); Florida East Coast Railway, Key West Extension of the Florida East Coast Railway, opened January 22, 1912 (1912), unpaginated, cited by scan image (archive.org keywestextension00flor, Smithsonian Libraries). All public domain (published in the United States before 1931).",
        "hinweis": "Every passage was read against the page image. The text follows the printing, including its spellings ('rythmical', 'threshhold', 'Estetta Keys'); words broken at the end of a line are joined. The 1905 article in the Railroad Gazette has lost a line in printing at the top of p. 326; the gap is marked in [8]. The booklet of 1912 has no page numbers: 'scan n22' is the image /page/n22 of the archive.org scan. The voices here are the railway's and the railway trade press's; the workers appear only as they described them. Their words about race and about the recruits are quoted as printed and marked as theirs in the notes.",
        "sections": sections,
    }
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")
    print(OUT.name, sum(len(s["units"]) for s in sections), "passages in", len(sections), "sections")


if __name__ == "__main__":
    main()
